version: '3'
services:
  web:
    build: .
    command: yarn start
    volumes:
    - .:/usr/app/
    - /usr/app/node_modules
    ports:
    - "3000:3000"
    depends_on:
    - db
    environment:
      DATABASE_URL: mongodb://db:27017/node-phones-api
      API_URL: http://web:3000
  db:
    image: mongo
    expose:
    - 27017
